import { z } from "zod";
import { createRouter, staffQuery, doctorQuery } from "./middleware";
import { getDb } from "./queries/connection";
import {
  prescriptions,
  prescriptionMedicines,
  prescriptionTests,
  patients,
  doctors,
} from "@db/schema";
import { eq, desc, inArray, and, isNull } from "drizzle-orm";
import { TRPCError } from "@trpc/server";
import { sendWhatsAppPrescription } from "./lib/whatsapp";
import { getPrescriptionSecureToken } from "./lib/pdf";
import { logActivity } from "./lib/activity";

export const prescriptionsRouter = createRouter({
  create: doctorQuery
    .input(
      z.object({
        patientId: z.number(),
        diagnosisNotes: z.string().min(1, "Diagnosis notes are required"),
        medicines: z.array(
          z.object({
            medicineName: z.string().min(1, "Medicine name is required"),
            dosage: z.string().min(1, "Dosage is required"),
            frequency: z.string().min(1, "Frequency is required"),
            duration: z.string().min(1, "Duration is required"),
            instructions: z.string().optional(),
          })
        ),
        tests: z.array(
          z.object({
            testName: z.string().min(1, "Test name is required"),
            notes: z.string().optional(),
          })
        ),
      })
    )
    .mutation(async ({ input, ctx }) => {
      const db = getDb();

      const [doctor] = await db
        .select()
        .from(doctors)
        .where(and(eq(doctors.userId, ctx.user.id), isNull(doctors.deletedAt)))
        .limit(1);

      if (!doctor) {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: "Logged-in user is not registered as a doctor.",
        });
      }

      const [patient] = await db
        .select()
        .from(patients)
        .where(and(eq(patients.id, input.patientId), isNull(patients.deletedAt)))
        .limit(1);

      if (!patient) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Patient not found" });
      }

      const [newPrescription] = await db
        .insert(prescriptions)
        .values({
          patientId: input.patientId,
          doctorId: doctor.id,
          diagnosisNotes: input.diagnosisNotes,
          status: "sent",
        })
        .returning();

      if (input.medicines.length > 0) {
        await db.insert(prescriptionMedicines).values(
          input.medicines.map((m) => ({
            prescriptionId: newPrescription.id,
            medicineName: m.medicineName,
            dosage: m.dosage,
            frequency: m.frequency,
            duration: m.duration,
            instructions: m.instructions || null,
          }))
        );
      }

      if (input.tests.length > 0) {
        await db.insert(prescriptionTests).values(
          input.tests.map((t) => ({
            prescriptionId: newPrescription.id,
            testName: t.testName,
            notes: t.notes || null,
            status: "pending" as const,
          }))
        );
      }

      await db
        .update(patients)
        .set({ status: "completed" })
        .where(eq(patients.id, input.patientId));

      const secureToken = getPrescriptionSecureToken(newPrescription.id);
      const origin = new URL(ctx.req.url).origin;
      const downloadUrl = `${origin}/api/prescriptions/${newPrescription.id}/pdf?token=${secureToken}`;

      let summary = `*APOLLO CLINIC PRESCRIPTION*\n`;
      summary += `Dear ${patient.name}, your digital prescription has been generated by Dr. ${doctor.name}.\n\n`;
      summary += `View & Download PDF:\n${downloadUrl}\n\n`;
      summary += `Thank you for choosing Apollo Clinic!`;
      await sendWhatsAppPrescription(patient.phone, summary);

      await logActivity(ctx.user, "create", "prescription", newPrescription.id,
        `Created prescription for patient #${input.patientId}`);

      return { success: true, prescriptionId: newPrescription.id };
    }),

  createFromScan: staffQuery
    .input(
      z.object({
        patientId: z.number(),
        doctorId: z.number(),
        diagnosisNotes: z.string().min(1, "Diagnosis notes are required"),
        medicines: z.array(
          z.object({
            medicineName: z.string().min(1, "Medicine name is required"),
            dosage: z.string().min(1, "Dosage is required"),
            frequency: z.string().min(1, "Frequency is required"),
            duration: z.string().min(1, "Duration is required"),
            instructions: z.string().optional(),
          })
        ),
        tests: z.array(
          z.object({
            testName: z.string().min(1, "Test name is required"),
            notes: z.string().optional(),
          })
        ),
      })
    )
    .mutation(async ({ input, ctx }) => {
      const db = getDb();

      const [doctor] = await db
        .select()
        .from(doctors)
        .where(and(eq(doctors.id, input.doctorId), isNull(doctors.deletedAt)))
        .limit(1);

      if (!doctor) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Selected doctor not found.",
        });
      }

      const [patient] = await db
        .select()
        .from(patients)
        .where(and(eq(patients.id, input.patientId), isNull(patients.deletedAt)))
        .limit(1);

      if (!patient) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Patient not found" });
      }

      const [newPrescription] = await db
        .insert(prescriptions)
        .values({
          patientId: input.patientId,
          doctorId: input.doctorId,
          diagnosisNotes: input.diagnosisNotes,
          status: "sent",
        })
        .returning();

      if (input.medicines.length > 0) {
        await db.insert(prescriptionMedicines).values(
          input.medicines.map((m) => ({
            prescriptionId: newPrescription.id,
            medicineName: m.medicineName,
            dosage: m.dosage,
            frequency: m.frequency,
            duration: m.duration,
            instructions: m.instructions || null,
          }))
        );
      }

      if (input.tests.length > 0) {
        await db.insert(prescriptionTests).values(
          input.tests.map((t) => ({
            prescriptionId: newPrescription.id,
            testName: t.testName,
            notes: t.notes || null,
            status: "pending" as const,
          }))
        );
      }

      await db
        .update(patients)
        .set({ status: "completed" })
        .where(eq(patients.id, input.patientId));

      const secureToken = getPrescriptionSecureToken(newPrescription.id);
      const origin = new URL(ctx.req.url).origin;
      const downloadUrl = `${origin}/api/prescriptions/${newPrescription.id}/pdf?token=${secureToken}`;

      let summary = `*APOLLO CLINIC PRESCRIPTION*\n`;
      summary += `Dear ${patient.name}, your digital prescription has been generated by Dr. ${doctor.name}.\n\n`;
      summary += `View & Download PDF:\n${downloadUrl}\n\n`;
      summary += `Thank you for choosing Apollo Clinic!`;
      await sendWhatsAppPrescription(patient.phone, summary);

      await logActivity(ctx.user, "create", "prescription", newPrescription.id,
        `Created prescription from scan for patient #${input.patientId}`);

      return { success: true, prescriptionId: newPrescription.id };
    }),

  getByPatientId: staffQuery
    .input(z.object({ patientId: z.number() }))
    .query(async ({ input }) => {
      const db = getDb();

      const [prescription] = await db
        .select({
          id: prescriptions.id,
          patientId: prescriptions.patientId,
          doctorId: prescriptions.doctorId,
          diagnosisNotes: prescriptions.diagnosisNotes,
          createdAt: prescriptions.createdAt,
          status: prescriptions.status,
          pharmacyBillingAmount: prescriptions.pharmacyBillingAmount,
          doctorName: doctors.name,
          doctorCredentials: doctors.credentials,
          doctorSpecialty: doctors.specialty,
          doctorRegNumber: doctors.registrationNumber,
          patientName: patients.name,
          patientAge: patients.age,
          patientGender: patients.gender,
          patientPhone: patients.phone,
        })
        .from(prescriptions)
        .leftJoin(doctors, eq(prescriptions.doctorId, doctors.id))
        .leftJoin(patients, eq(prescriptions.patientId, patients.id))
        .where(and(eq(prescriptions.patientId, input.patientId), isNull(prescriptions.deletedAt)))
        .orderBy(desc(prescriptions.createdAt))
        .limit(1);

      if (!prescription) {
        return null;
      }

      const medicines = await db
        .select()
        .from(prescriptionMedicines)
        .where(eq(prescriptionMedicines.prescriptionId, prescription.id));

      const tests = await db
        .select()
        .from(prescriptionTests)
        .where(eq(prescriptionTests.prescriptionId, prescription.id));

      return { ...prescription, medicines, tests };
    }),

  listSent: staffQuery.query(async () => {
    const db = getDb();

    const list = await db
      .select({
        id: prescriptions.id,
        patientId: prescriptions.patientId,
        diagnosisNotes: prescriptions.diagnosisNotes,
        createdAt: prescriptions.createdAt,
        status: prescriptions.status,
        pharmacyBillingAmount: prescriptions.pharmacyBillingAmount,
        patientName: patients.name,
        patientPhone: patients.phone,
        patientAge: patients.age,
        patientGender: patients.gender,
        doctorName: doctors.name,
        doctorSpecialty: doctors.specialty,
      })
      .from(prescriptions)
      .innerJoin(patients, eq(prescriptions.patientId, patients.id))
      .innerJoin(doctors, eq(prescriptions.doctorId, doctors.id))
      .where(and(
        inArray(prescriptions.status, ["sent", "dispensed"]),
        isNull(prescriptions.deletedAt),
      ))
      .orderBy(desc(prescriptions.createdAt));

    const enriched = await Promise.all(
      list.map(async (p) => {
        const medicines = await db
          .select()
          .from(prescriptionMedicines)
          .where(eq(prescriptionMedicines.prescriptionId, p.id));

        const tests = await db
          .select()
          .from(prescriptionTests)
          .where(eq(prescriptionTests.prescriptionId, p.id));

        return { ...p, medicines, tests };
      })
    );

    return enriched;
  }),

  updateTestStatus: staffQuery
    .input(
      z.object({
        id: z.number(),
        status: z.enum(["pending", "completed"]),
        notes: z.string().optional(),
      })
    )
    .mutation(async ({ input, ctx }) => {
      const db = getDb();
      await db
        .update(prescriptionTests)
        .set({ status: input.status, notes: input.notes || null })
        .where(eq(prescriptionTests.id, input.id));
      await logActivity(ctx.user, "update", "prescription_test", input.id,
        `Updated test status to ${input.status}`);
      return { success: true };
    }),

  updateStatus: staffQuery
    .input(
      z.object({
        id: z.number(),
        status: z.enum(["draft", "sent", "dispensed"]),
      })
    )
    .mutation(async ({ input, ctx }) => {
      const db = getDb();
      await db
        .update(prescriptions)
        .set({ status: input.status })
        .where(eq(prescriptions.id, input.id));
      await logActivity(ctx.user, "update", "prescription", input.id,
        `Updated prescription status to ${input.status}`);
      return { success: true };
    }),

  dispenseMedicines: staffQuery
    .input(
      z.object({
        prescriptionId: z.number(),
        medicineIds: z.array(z.number()),
        billingAmount: z.number(),
      })
    )
    .mutation(async ({ input, ctx }) => {
      const db = getDb();

      if (input.medicineIds.length > 0) {
        await db
          .update(prescriptionMedicines)
          .set({ status: "purchased" as const })
          .where(
            and(
              eq(prescriptionMedicines.prescriptionId, input.prescriptionId),
              inArray(prescriptionMedicines.id, input.medicineIds)
            )
          );
      }

      const allMedicines = await db
        .select()
        .from(prescriptionMedicines)
        .where(eq(prescriptionMedicines.prescriptionId, input.prescriptionId));

      const allPurchased = allMedicines.every((m) => m.status === "purchased");

      const [currentPrescription] = await db
        .select({ pharmacyBillingAmount: prescriptions.pharmacyBillingAmount })
        .from(prescriptions)
        .where(eq(prescriptions.id, input.prescriptionId))
        .limit(1);

      const existingAmount = currentPrescription?.pharmacyBillingAmount || 0;
      const newAmount = existingAmount + input.billingAmount;

      await db
        .update(prescriptions)
        .set({
          status: allPurchased ? ("dispensed" as const) : ("sent" as const),
          pharmacyBillingAmount: newAmount,
        })
        .where(eq(prescriptions.id, input.prescriptionId));

      await logActivity(ctx.user, "update", "prescription", input.prescriptionId,
        `Dispensed medicines worth ₹${input.billingAmount}`);

      return { success: true };
    }),
});
